apiVersion: v1
kind: Service
metadata:
  name: alia-tokenizer-comparison
  namespace: labs
  labels:
    app.kubernetes.io/part-of: labs
    app.kubernetes.io/name: alia-tokenizer-comparison
spec:
  selector:
    app: alia-tokenizer-comparison
  ports:
    - name: http
      port: 80
      targetPort: 8080
